#!/bin/sh

news_dir=$HOME/news
news_file=
load_news()
{
    if [ ! -d $news_dir ]
    then
        mkdir -p "$news_dir"
    fi
    local news_in_hours=$news_dir/$(date +'%F')*
    rm $news_in_hours > /dev/null 2>&1 3>&1

    news_file=$news_dir/$(date +'%F %R')
    curl -sL https://www.toutiao.com/hot-event/hot-board/?origin=toutiao_pc -o "$news_file"

    echo "loading $(date) news complete."
}

verbose=0
while getopts fvi: option
do case "${option}" in
    f) load_news
       shift;;
    v) verbose=1
       shift;;
    i) seq=${OPTARG};;
    [?])  echo "Usage: $0 [-f force refresh] [-v verbose] ..."
    esac
done

seq=$1
#echo "verbose $verbose seq $seq $1"

find_news_file()
{
    news_file=$(ls "$news_dir" | grep "$(date +'%F')*")
    echo "find today news: $news_file"
    news_file=$news_dir/$news_file
}

show_news_detail()
{
    if [ "$seq" != "" ] && [ "$seq" -eq "$seq" ] 2>/dev/null; then
        cat "$news_file" | python3 -c "import sys, json, string; list=json.load(sys.stdin)['data']; [print(str(i+1)+'.'+list[i]['Title']+'\n'+list[i]['Url']) for i in range(len(list))];" | grep -A 1 "^$seq\."
    elif [ $verbose == 1 ]; then
        cat "$news_file" | python3 -c "import sys, json, string; list=json.load(sys.stdin)['data']; [print(str(i+1)+'.'+list[i]['Title']+list[i]['Url']) for i in range(len(list))];"
    else 
        cat "$news_file" | python3 -c "import sys, json, string; list=json.load(sys.stdin)['data']; [print(str(i+1)+'.'+list[i]['Title']) for i in range(len(list))];"
    fi
}

if [ -z "$news_file" ];then
    find_news_file
fi

if test -f "$news_file"
then
    echo "open $news_file"
    show_news_detail    
else
    load_news
    show_news_detail
fi


