#!/bin/sh

#echo "args:$# $*" 

news_dir=$HOME/news
news_file=
current_day=$(date +'%F')
is_history=0
load_news()
{
    if [ ! -d $news_dir ]
    then
        mkdir -p "$news_dir"
    fi
    local news_in_hours="$news_dir/$current_day"*
    rm $news_in_hours > /dev/null 2>&1 3>&1

    news_file=$news_dir/$(date +'%F %R')
    curl -sL https://www.toutiao.com/hot-event/hot-board/?origin=toutiao_pc -o "$news_file"

    echo "loading $(date) news complete."
}

verbose=0
while getopts fvd:i: option
do case "${option}" in
    f) load_news
        ;;
    v) verbose=1
        ;;
    d) current_day=${OPTARG}
       is_history=1
        ;; 
    i) seq=${OPTARG}
        ;;
    [?]) echo "Usage: $0 [-f force refresh] [-v verbose] ..."
    esac
done

shift $((OPTIND-1))

if [ -z $seq ]; then 
    seq=$1
fi
#echo "args:$# $* verbose $verbose seq $seq $1"

find_news_file()
{
    echo "$current_day"
    news_file=$(ls "$news_dir" | grep -m 1 "$current_day *")
    echo "find day news: '$news_file'"
    news_file="$news_dir/$news_file"
}

format_news()
{
    if [ $1 = 1 ]; then
        cat "$news_file" | python3 -c "import sys, json, string; list=json.load(sys.stdin)['data']; [print(str(i+1)+'.'+list[i]['Title']+'\n'+list[i]['Url']) for i in range(len(list))];"
    else 
        cat "$news_file" | python3 -c "import sys, json, string; list=json.load(sys.stdin)['data']; [print(str(i+1)+'.'+list[i]['Title']) for i in range(len(list))];"
    fi
}

show_news_detail()
{
    local pattern="$seq"
    if [ "$seq" -eq "$seq" ] 2>/dev/null; then
        verbose=1
        pattern="^$seq\."
    fi
    local cxt=
    if [ $verbose = 1 ] 2>/dev/null;then
        cxt="-A 1"
    fi
    if [ "$pattern" != "" ] 2>/dev/null; then
        format_news $verbose | grep $cxt "$pattern"
    else
        format_news $verbose
    fi
}

if [ -z "$news_file" ];then
    find_news_file
fi

if test -f "$news_file"
then
    echo "open $news_file"
    show_news_detail    
else
    load_news
    show_news_detail
fi


