#!/bin/sh

news_dir=$(pwd)
news_in_hours=$news_dir/$(date +'%F')*
rm $news_in_hours

file=$news_dir/$(date +'%F %R')
curl -sL https://www.toutiao.com/hot-event/hot-board/?origin=toutiao_pc -o "$file"

echo "loading $(date) new complete."

#cat "$file" | python -m json.tool 

