#!/bin/sh

news_dir=$(pwd)
news_in_hours=$news_dir/$(date +'%F')*
rm $news_in_hours

file=$news_dir/$(date +'%F %R')
curl -sL https://www.toutiao.com/hot-event/hot-board/?origin=toutiao_pc -o "$file"

echo "loading $(date) new complete."

#cat "$file" | python -m json.tool 

echo "args : $1"
if [ $1 == "-v" ]
then

cat "$file" | python3 -c "import sys, json, string; list=json.load(sys.stdin)['data']; [print(i['Title']+'\n'+i['Url']) for i in list];"

else

cat "$file" | python3 -c "import sys, json, string; list=json.load(sys.stdin)['data']; [print(i['Title']) for i in list];"

fi
